name: farmerfieldmanagement
description: A farmer field management mobile application.

# Version Control
version: 1.0.0+1

# Flutter SDK Environment
environment:
  sdk: '>=3.1.3 <4.0.0'

# Dependencies
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2  # iOS style icons
  connectivity_plus: ^3.0.6  # Network status handling
  google_maps_flutter: ^2.1.1 # For GPS and maps integration
  charts_flutter: ^0.12.0  # For data analytics visualization
  carousel_slider: ^4.0.0


  # Firebase Dependencies (compatible versions for Dart SDK 3.1.3)
  firebase_core: ^2.12.0   # Firebase core package
  firebase_auth: ^4.8.0    # Firebase Authentication
  cloud_firestore: ^4.8.0  # Firestore Database
  firebase_storage: ^11.2.0  # Firebase Storage for files

  # HTTP requests
  http: ^1.0.0  # Latest compatible version for HTTP requests

  # State Management
  provider: ^6.0.5  # Compatible version for managing app state

  # Local Storage
  shared_preferences: ^2.1.0  # To store data locally on the device

# Development Dependencies (for testing, linting, etc.)
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0  # Linting to ensure best practices
  google_fonts: ^6.2.0  # Google Fonts for custom font integration
  font_awesome_flutter: ^10.1.0  # Font Awesome Icons
  http: ^1.0.0  # Ensure this is also included in dev dependencies for consistency

# Flutter specific configurations
flutter:
  uses-material-design: true

  # Assets declaration: Images, data files, etc.
  assets:
    - assets/farm_background.jpg
    - assets/field_management.jpg
    - assets/resource_management.jpg
    - assets/analytics.jpg
    - assets/promotion.jpg
    - assets/weather_forecast.jpg
    - assets/fertilizer_offer.jpg
    - assets/carousel1.jpg
    - assets/carousel2.jpg
    - assets/carousel3.jpg

  # Fonts: Uncomment and customize if you need custom fonts
#  fonts:
#    - family: CustomFont
#      fonts:
#        - asset: fonts/CustomFont-Regular.ttf
#        - asset: fonts/CustomFont-Bold.ttf
#          weight: 700
